export { default as Home } from "./Home"
export { default as SignUp } from "./SignUp"
export { default as Login } from "./Login"
export { default as ResetPassword } from "./ResetPassword"
export { default as SideBar } from "./SideBar"